### ISSUE TITLE
DreamObjects URL Changing

### ISSUE THREAD

**Issue by frogcm** [Ipstenu/dreamobjects#12]
The DreamObjects URL is changing from objects.dreamhost.com on September 5th, 2016. It is currently hard-coded in a few files:

admin/backups-retain.php
lib/dhdo.php
lib/settings.php

Without any guarantees that it will stay static at the new URL, the base_url should be made into an option alongside the key and secretkey.

(Thanks for all of your great work on this plugin. We appreciate the easy backups to DreamObjects.)

**Comment by Ipstenu** [comment]
Already in progress at https://github.com/Ipstenu/dreamobjects/tree/REL_4.0.2 :)
