### ISSUE TITLE
Backup is stuck in Backup in Progress

### ISSUE THREAD

**Issue by youngcm2** [Ipstenu/dreamobjects#13]
It has been like this for 24hours. I have tried changing setting, deactivating. Here is a screen shot.
![screen shot 2017-01-17 at 8 53 47 am](https://cloud.githubusercontent.com/assets/862338/22025274/a11659ce-dc92-11e6-97bb-41db629faede.png)

How can I restart it?

**Comment by Ipstenu** [comment]
Support posts should go at https://wordpress.org/support/plugin/dreamobjects

That's a pretty odd thing to happen and means that cron isn't running properly.

Go to yourdomain.com/wp-cron.php?doing=cron

If that doesn't make it work, you'll need to install https://wordpress.org/plugins/wp-crontrol/ and look for a cron job called `dh-do-backupnow`

Force run it OR delete it.
