### ISSUE TITLE
Fails to backup my database

### ISSUE THREAD

**Issue by thinsoldier** [Ipstenu/dreamobjects#6]
Doesn't matter if I choose just database or both database and all files.

The zip files contain /wp-content/upgrade/dreamobject-db-backup.sql which is always an empty file.

**Comment by thinsoldier** [comment]
I'm trying to get xdebug working so I can step through the code as it executes and hopefully see what's going wrong when it gets to the database related code.

**Comment by Ipstenu** [comment]
Sadly I've just not been able to reproduce it on any setup I built.

**Comment by Ipstenu** [comment]
I was never able to reproduce this :(
